// StockSense - Initial Sample Data
// Seed data for hackathon demo to ensure immediate visual richness and testing

const DEFAULT_WAREHOUSES = [
  { id: 'wh-alpha', name: 'Warehouse Alpha (Central Hub - Chicago)', code: 'W-CHI', location: 'Chicago, IL', capacity: 15000 },
  { id: 'wh-bravo', name: 'Warehouse Bravo (West Coast Depot - Seattle)', code: 'W-SEA', location: 'Seattle, WA', capacity: 10000 },
  { id: 'wh-charlie', name: 'Warehouse Charlie (East Port Logistics - NJ)', code: 'W-NJ', location: 'Elizabeth, NJ', capacity: 18000 },
  { id: 'wh-delta', name: 'Warehouse Delta (Southern Gateway - Dallas)', code: 'W-DAL', location: 'Dallas, TX', capacity: 12000 }
];

const DEFAULT_CATEGORIES = [
  'Electronics & Hardware',
  'PPE & Safety Gear',
  'Packaging & Shipping',
  'Heavy Machinery & Tools',
  'Office & IT Equipment',
  'Medical & First Aid'
];

const DEFAULT_PRODUCTS = [
  {
    id: 'prod-001',
    name: 'Industrial Rugged Barcode Scanner 2D',
    sku: 'ELEC-SCN-201',
    category: 'Electronics & Hardware',
    quantity: 45,
    price: 349.99,
    warehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    minThreshold: 15,
    location: 'Aisle A-03, Bin 12',
    unit: 'Units',
    description: 'IP65 drop-resistant wireless barcode scanner with Bluetooth cradle and high-speed CMOS sensor.',
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString()
  },
  {
    id: 'prod-002',
    name: 'N95 Particulate Respirator Mask (Box 50)',
    sku: 'PPE-MSK-092',
    category: 'PPE & Safety Gear',
    quantity: 8,
    price: 42.50,
    warehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    minThreshold: 25,
    location: 'Aisle B-01, Bin 04',
    unit: 'Boxes',
    description: 'NIOSH certified N95 particle filter respirator with adjustable nose clip.',
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString()
  },
  {
    id: 'prod-003',
    name: 'Thermal Transfer Shipping Labels 4x6" (Roll of 1000)',
    sku: 'PKG-LBL-406',
    category: 'Packaging & Shipping',
    quantity: 0,
    price: 18.75,
    warehouse: 'Warehouse Charlie (East Port Logistics - NJ)',
    minThreshold: 30,
    location: 'Aisle C-04, Bin 18',
    unit: 'Rolls',
    description: 'Standard fanfold 4x6 direct thermal commercial shipping labels. Out of stock - reorder urgent.',
    updatedAt: new Date(Date.now() - 3600000 * 24).toISOString()
  },
  {
    id: 'prod-004',
    name: 'Hydraulic Hand Pallet Jack 5,500 lbs Capacity',
    sku: 'MCH-PLT-550',
    category: 'Heavy Machinery & Tools',
    quantity: 14,
    price: 489.00,
    warehouse: 'Warehouse Delta (Southern Gateway - Dallas)',
    minThreshold: 5,
    location: 'Zone D-Floor, Staging 2',
    unit: 'Units',
    description: 'Heavy gauge steel hydraulic pallet truck with polyurethane steer wheels and overload valve.',
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString()
  },
  {
    id: 'prod-005',
    name: 'Lithium-Ion Forklift Battery Pack 48V 600Ah',
    sku: 'ELEC-BAT-48V',
    category: 'Electronics & Hardware',
    quantity: 3,
    price: 4200.00,
    warehouse: 'Warehouse Bravo (West Coast Depot - Seattle)',
    minThreshold: 6,
    location: 'Zone H-Hazmat, Bay 01',
    unit: 'Units',
    description: 'High density fast-charge industrial lithium battery pack with integrated CAN-bus BMS.',
    updatedAt: new Date(Date.now() - 3600000 * 18).toISOString()
  },
  {
    id: 'prod-006',
    name: 'High-Visibility Class 2 Reflective Safety Vests',
    sku: 'PPE-VST-101',
    category: 'PPE & Safety Gear',
    quantity: 85,
    price: 14.20,
    warehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    minThreshold: 20,
    location: 'Aisle B-02, Bin 09',
    unit: 'Units',
    description: 'ANSI/ISEA compliant breathable neon yellow reflective vest with multiple gear pockets.',
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString()
  },
  {
    id: 'prod-007',
    name: 'Cat6 Pure Copper Bulk Cable Reel 1,000 ft',
    sku: 'IT-CAT6-100',
    category: 'Office & IT Equipment',
    quantity: 6,
    price: 175.50,
    warehouse: 'Warehouse Bravo (West Coast Depot - Seattle)',
    minThreshold: 15,
    location: 'Aisle E-01, Shelf 3',
    unit: 'Rolls',
    description: 'Solid pure bare copper 550MHz UTP plenum rated Ethernet communication cable.',
    updatedAt: new Date(Date.now() - 3600000 * 30).toISOString()
  },
  {
    id: 'prod-008',
    name: 'Heavy Duty Stretch Wrap Film 18" x 1500ft',
    sku: 'PKG-STW-180',
    category: 'Packaging & Shipping',
    quantity: 110,
    price: 26.80,
    warehouse: 'Warehouse Charlie (East Port Logistics - NJ)',
    minThreshold: 40,
    location: 'Aisle C-01, Pallet 05',
    unit: 'Rolls',
    description: '80-gauge cast industrial hand stretch wrap with superior puncture resistance.',
    updatedAt: new Date(Date.now() - 3600000 * 6).toISOString()
  },
  {
    id: 'prod-009',
    name: 'ANSI Hard Hats with Ratchet Suspension',
    sku: 'PPE-HAT-305',
    category: 'PPE & Safety Gear',
    quantity: 62,
    price: 22.90,
    warehouse: 'Warehouse Delta (Southern Gateway - Dallas)',
    minThreshold: 20,
    location: 'Aisle B-03, Bin 11',
    unit: 'Units',
    description: 'High-density polyethylene shell impact hard hat with 6-point suspension system.',
    updatedAt: new Date(Date.now() - 3600000 * 14).toISOString()
  },
  {
    id: 'prod-010',
    name: 'Industrial First Aid & Burn Trauma Station',
    sku: 'MED-FAS-050',
    category: 'Medical & First Aid',
    quantity: 18,
    price: 129.00,
    warehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    minThreshold: 10,
    location: 'Aisle F-01, Wall 02',
    unit: 'Kits',
    description: 'OSHA 1910 and ANSI compliant 4-shelf wall mounted emergency medical station.',
    updatedAt: new Date(Date.now() - 3600000 * 48).toISOString()
  },
  {
    id: 'prod-011',
    name: 'Corrugated Double-Wall Shipping Cartons 24x18x18"',
    sku: 'PKG-BOX-241',
    category: 'Packaging & Shipping',
    quantity: 320,
    price: 4.85,
    warehouse: 'Warehouse Charlie (East Port Logistics - NJ)',
    minThreshold: 100,
    location: 'Zone C-Staging, Rack 12',
    unit: 'Units',
    description: 'ECT-48 heavy-duty corrugated cardboard shipping boxes for parcel dispatch.',
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString()
  },
  {
    id: 'prod-012',
    name: 'Cordless Brushless Impact Driver Kit 20V',
    sku: 'MCH-IMP-20V',
    category: 'Heavy Machinery & Tools',
    quantity: 22,
    price: 199.95,
    warehouse: 'Warehouse Delta (Southern Gateway - Dallas)',
    minThreshold: 8,
    location: 'Aisle D-02, Shelf 04',
    unit: 'Kits',
    description: 'Compact high-torque 2050 in-lbs impact driver with two 4Ah batteries and rapid charger.',
    updatedAt: new Date(Date.now() - 3600000 * 9).toISOString()
  },
  {
    id: 'prod-013',
    name: 'Hydraulic Cylinder Seal Repair Kit Series-X',
    sku: 'MCH-SLK-009',
    category: 'Heavy Machinery & Tools',
    quantity: 5,
    price: 88.00,
    warehouse: 'Warehouse Bravo (West Coast Depot - Seattle)',
    minThreshold: 15,
    location: 'Aisle D-04, Bin 02',
    unit: 'Kits',
    description: 'Complete nitrile and polyurethane sealing kit for industrial forklift lift cylinders.',
    updatedAt: new Date(Date.now() - 3600000 * 20).toISOString()
  },
  {
    id: 'prod-014',
    name: 'Enterprise Wi-Fi 6 Industrial Access Point',
    sku: 'IT-WAP-600',
    category: 'Office & IT Equipment',
    quantity: 19,
    price: 520.00,
    warehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    minThreshold: 8,
    location: 'Aisle E-02, Shelf 01',
    unit: 'Units',
    description: 'Ruggedized IP67 weatherproof 4x4 MU-MIMO dual-band wireless gateway with PoE+ support.',
    updatedAt: new Date(Date.now() - 3600000 * 7).toISOString()
  },
  {
    id: 'prod-015',
    name: 'Nitrile Heavy-Duty Disposable Gloves 6mil (Box 100)',
    sku: 'PPE-GLV-006',
    category: 'PPE & Safety Gear',
    quantity: 145,
    price: 16.50,
    warehouse: 'Warehouse Bravo (West Coast Depot - Seattle)',
    minThreshold: 50,
    location: 'Aisle B-04, Bin 19',
    unit: 'Boxes',
    description: 'Powder-free chemical resistant textured grip black nitrile examination gloves.',
    updatedAt: new Date(Date.now() - 3600000 * 3).toISOString()
  },
  {
    id: 'prod-016',
    name: 'Waterproof Digital Inventory Scale 600 lbs',
    sku: 'ELEC-SCL-600',
    category: 'Electronics & Hardware',
    quantity: 9,
    price: 360.00,
    warehouse: 'Warehouse Delta (Southern Gateway - Dallas)',
    minThreshold: 4,
    location: 'Zone D-Bench, Bay 03',
    unit: 'Units',
    description: 'Stainless steel washdown platform scale with backlit LCD and RS232 serial printer output.',
    updatedAt: new Date(Date.now() - 3600000 * 16).toISOString()
  }
];

const DEFAULT_TRANSACTIONS = [
  {
    id: 'tx-1001',
    productId: 'prod-001',
    productName: 'Industrial Rugged Barcode Scanner 2D',
    sku: 'ELEC-SCN-201',
    type: 'STOCK_IN',
    quantity: 25,
    balanceAfter: 45,
    sourceWarehouse: '',
    targetWarehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    reference: 'PO-2026-8891',
    operator: 'Sarah Jenkins (Logistics Mgr)',
    notes: 'Received initial shipment from Honeywell OEM supplier.',
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString()
  },
  {
    id: 'tx-1002',
    productId: 'prod-008',
    productName: 'Heavy Duty Stretch Wrap Film 18" x 1500ft',
    sku: 'PKG-STW-180',
    type: 'STOCK_OUT',
    quantity: 30,
    balanceAfter: 110,
    sourceWarehouse: 'Warehouse Charlie (East Port Logistics - NJ)',
    targetWarehouse: '',
    reference: 'DISP-7721',
    operator: 'Marcus Vance (Warehouse Staff)',
    notes: 'Dispatched to outbound fulfillment bays 3 & 4.',
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString()
  },
  {
    id: 'tx-1003',
    productId: 'prod-005',
    productName: 'Lithium-Ion Forklift Battery Pack 48V 600Ah',
    sku: 'ELEC-BAT-48V',
    type: 'TRANSFER',
    quantity: 2,
    balanceAfter: 3,
    sourceWarehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    targetWarehouse: 'Warehouse Bravo (West Coast Depot - Seattle)',
    reference: 'XFER-00941',
    operator: 'Elena Rostova (Fleet Specialist)',
    notes: 'Inter-facility transfer to replenish West Coast fleet maintenance.',
    timestamp: new Date(Date.now() - 3600000 * 18).toISOString()
  },
  {
    id: 'tx-1004',
    productId: 'prod-002',
    productName: 'N95 Particulate Respirator Mask (Box 50)',
    sku: 'PPE-MSK-092',
    type: 'STOCK_OUT',
    quantity: 15,
    balanceAfter: 8,
    sourceWarehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    targetWarehouse: '',
    reference: 'SO-99231',
    operator: 'David Kim (Inventory Clerk)',
    notes: 'Safety distribution to Regional Plant #4. Stock dropped below reorder threshold.',
    timestamp: new Date(Date.now() - 3600000 * 8).toISOString()
  },
  {
    id: 'tx-1005',
    productId: 'prod-003',
    productName: 'Thermal Transfer Shipping Labels 4x6" (Roll of 1000)',
    sku: 'PKG-LBL-406',
    type: 'STOCK_OUT',
    quantity: 40,
    balanceAfter: 0,
    sourceWarehouse: 'Warehouse Charlie (East Port Logistics - NJ)',
    targetWarehouse: '',
    reference: 'DISP-7750',
    operator: 'Marcus Vance (Warehouse Staff)',
    notes: 'High-volume seasonal dispatch consumed entire reserve. Stock reached ZERO.',
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString()
  },
  {
    id: 'tx-1006',
    productId: 'prod-011',
    productName: 'Corrugated Double-Wall Shipping Cartons 24x18x18"',
    sku: 'PKG-BOX-241',
    type: 'STOCK_IN',
    quantity: 200,
    balanceAfter: 320,
    sourceWarehouse: '',
    targetWarehouse: 'Warehouse Charlie (East Port Logistics - NJ)',
    reference: 'PO-2026-9042',
    operator: 'Sarah Jenkins (Logistics Mgr)',
    notes: 'Bulk pallet delivery from International Paper packaging.',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString()
  },
  {
    id: 'tx-1007',
    productId: 'prod-006',
    productName: 'High-Visibility Class 2 Reflective Safety Vests',
    sku: 'PPE-VST-101',
    type: 'TRANSFER',
    quantity: 20,
    balanceAfter: 85,
    sourceWarehouse: 'Warehouse Delta (Southern Gateway - Dallas)',
    targetWarehouse: 'Warehouse Alpha (Central Hub - Chicago)',
    reference: 'XFER-00948',
    operator: 'Alex Rivera (Dock Lead)',
    notes: 'Seasonal staff onboarding reallocation to Central hub.',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString()
  }
];
